### ISSUE TITLE
how to use this action with a preview url

### ISSUE THREAD

**Issue by dagda1** [WPO-Foundation/webpagetest-github-action#7]
I am trying to use this action with a verbal preview url:

```yml
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
        id: vercel_preview_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 200
      
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The action errors with:

```
Run WPO-Foundation/webpagetest-github-action@main
  with:
    apiKey: ***
    urls: 
  
    label: GitHub Action Test
    GITHUB_TOKEN: ***
WebPageTest Configuration
  WebPageTest settings: {
    "firstViewOnly": true,
    "runs": 3,
    "location": "Dulles:Chrome",
    "connectivity": "4G",
    "pollResults": 5,
    "timeout": 240,
    "emulateMobile": true,
    "label": "GitHub Action Test"
  }
Testing urls in WebPageTest..
  Submitting test for  ...
  Error: Action failed with error [object Object]
```

Is there a way I can get a better error message than `[object Object]`?
